### ISSUE TITLE
wordpress channel no longer works

### ISSUE THREAD

**Issue by mandy3d** [mcolyer/hacklet-remote#5]
Hi! I can't get ifttt wordpress channel to accept my ip address is there anything else I can do?  I believe using the Wordpress channel is outdated.  Maybe you know how to use the webhooks. Thanks.

**Comment by mcolyer** [comment]
> using the Wordpress channel is outdated

You're totally right, the webhook channel didn't exist when I wrote but it's much more straightforward to use.

> Maybe you know how to use the webhooks. Thanks.

This will require some code changes. Would you be interested in helping?

**Comment by mandy3d** [comment]
I'm not much of a programmer but if you give me a summary of the changes maybe I can work it out. Thanks!

**Comment by mcolyer** [comment]
@mandy3d so I rewrote things to work. Can you check out #6 and see if you can get it configured?

**Comment by mandy3d** [comment]
Can I say I'm super shocked you did this and I'm thrilled I'll try it out
tonight.

Mandy

**Comment by mandy3d** [comment]
Been giving it a try.  However, even trying to go to my ip address and 9292 I don't get the word hacklet anymore.  I've also tried sending web requests and nothing happens at all.  Is there any tests I can run to help out?  I checked out the branch which i believe is the correct method for using a branch...

**Comment by mandy3d** [comment]
Okay! So I did get it to work but only on local host.  I get a sinatra error that it doesn't know this ditty which I think makes sense since I'm not sending a proper request.  So my main problem now is to get it to not only be localhost.

**Comment by mandy3d** [comment]
I got it after all I had to use bundle exec to get it to work

**Comment by mcolyer** [comment]
Awesome! Glad to hear you got it working. I'll merge this in when I get a
chance. Is there anything I should add to the docs to make it more clear
how to get started?

**Comment by mandy3d** [comment]
I had to reinstall ruby, and bundler. It requires at least Ruby 2.2.2 .  And the only only thing I did was instead of rake run I used bundle exec rackup -p9292 --host 0.0.0.0

**Comment by mandy3d** [comment]
Oh, thought I'd tell you what I'm using mine for. I can control my AC unit now with Google Assistant. I also plan on getting Thermopeanut to use as a thermostat unless you have tips on how to use the thermostat that came with the modlet AC kit.

**Comment by mcolyer** [comment]
> It requires at least Ruby 2.2.2 .

👍, I added that to the README.

>  bundle exec rackup -p9292 --host 0.0.0.0

I updated `rake run` to use that command instead.

> unless you have tips on how to use the thermostat that came with the modlet AC kit.

Unfortunately I didn't have access to the modlet AC kit when I built hacklet originally, so I have no idea if it uses similar commands or not. Your setup sounds like you should be able to accomplish the same thing though.

**Comment by mandy3d** [comment]
You may want to add instructions for it to autostart. I'm using foreman and systemmd to get it done. I found the instructions online pretty easily. Again, i'm not a programmer and it wasn't hard.

**Comment by mandy3d** [comment]
Thank you so much for your help.  Nicest person I've dealt with on github.  I feel like I upgraded my AC unit immensely and didn't cost me anything other than the new thermostat I'm going to get.

**Comment by mcolyer** [comment]
> Nicest person I've dealt with on github

Thanks (I actually work there)! Glad I could help out.

> I'm using foreman and systemmd to get it done

Yep that make sense, I'll take a look at adding that.
